Feature 106 refine time entry
Metatavu/vp-kuljetus-transport-management-specs pull request #107
Opened 2024-08-28 11:05 UTC by villejuutila

Resolves #106

2024-08-29 07:26 UTC, anttileppa requested changes

2024-08-29 07:26 UTC, anttileppa commented on services/user-management-services.yaml
>          - name: start
should these filter be replaced by range (after and before)?

2024-08-29 07:29 UTC, anttileppa requested changes

2024-08-29 07:29 UTC, anttileppa commented on services/user-management-services.yaml
> +          description: work events id
```suggestion
          description: work event's ID
```

2024-08-29 07:29 UTC, anttileppa commented on services/user-management-services.yaml
> +          description: employees id
```suggestion
          description: employee's ID
```

2024-08-29 07:29 UTC, anttileppa commented on services/user-management-services.yaml
> +          description: work events id
```suggestion
          description: work event's id
```

2024-08-29 07:29 UTC, anttileppa commented on services/user-management-services.yaml
> +          description: work events id
```suggestion
          description: work event's ID
```

2024-08-29 10:26 UTC, villejuutila commented on services/user-management-services.yaml
>          - name: start
Sounds reasonable. Done.

2024-08-29 10:29 UTC, villejuutila commented on services/user-management-services.yaml
> +          description: work events id
Resolved

2024-08-29 10:31 UTC, villejuutila commented on services/user-management-services.yaml
> +          description: employees id
Resolved

2024-08-29 10:31 UTC, villejuutila commented on services/user-management-services.yaml
> +          description: work events id
Resolved

2024-08-29 10:31 UTC, villejuutila commented on services/user-management-services.yaml
> +          description: work events id
Resolved

2024-09-02 10:12 UTC, anttileppa approved these changes

2024-09-04 09:39 UTC, merged