Added client apps
Metatavu/vp-kuljetus-transport-management-specs pull request #117
Opened 2024-09-27 13:13 UTC by lauriLukkarinen

Resolves #116

2024-10-01 14:01 UTC, anttileppa requested changes

2024-10-01 15:21 UTC, lauriLukkarinen commented on services/user-management-services.yaml
> +        - ApiKeyAuth: []
That was a leftover from the create, I'll remove that.

2024-10-01 15:23 UTC, lauriLukkarinen commented on services/user-management-services.yaml
> +          additionalProperties:
That seems reasonable. I'll add first version with those three values.

2024-10-04 06:17 UTC, anttileppa approved these changes

2024-10-04 06:39 UTC, merged