added missing data receiver endpoints for temperatures
Metatavu/vp-kuljetus-transport-management-specs pull request #145
Opened 2024-12-19 09:12 UTC by kaeline

2024-12-19 09:17 UTC, Daniilmass commented on input/vehicle-management-services.yaml
> +          description: Unique mac address for the temperature record
```suggestion
          description: Unique mac address of the thermometer that is sending this temperature reading
```

2024-12-19 09:18 UTC, Daniilmass approved these changes

2024-12-20 10:19 UTC, lauriLukkarinen requested changes

2024-12-23 10:49 UTC, kaeline commented on input/vehicle-management-services.yaml
> +          description: The IMEI of the truck/towable that is sending this temperature reading
As discussed earlier, I will stick to deviceIdentifier for clarity

2024-12-23 10:52 UTC, kaeline commented on input/vehicle-management-services.yaml
> +          description: The IMEI of the truck/towable that is sending this temperature reading
As discussed earlier, I will stick to deviceIdentifier for clarity

2025-01-10 06:03 UTC, merged